version: '3.4'

services:

  exercisemanager:
    build:
      context: .
      dockerfile: ./ExerciseManager/Dockerfile
      args:
        INSTALL_LIB: 1
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./logs:/app/logs

  tanksimulator:
    build:
      context: .
      dockerfile: ./TankSimulator/Dockerfile
      args:
        INSTALL_LIB: 1
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./logs:/app/logs

